apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  creationTimestamp: "2019-11-01T22:54:45Z"
  name: gp2
  resourceVersion: "171"
  selfLink: /apis/storage.k8s.io/v1/storageclasses/gp2
  uid: 98fcc3bb-fcfa-11e9-b89f-067d170cd2f4
parameters:
  fsType: ext4
  type: gp2
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
volumeBindingMode: Immediate

